package io.mverse.kslack.api.methods.request.team

import io.mverse.kslack.api.methods.SlackApiRequest

data class TeamIntegrationLogsRequest(

  /**
   * Authentication token. Requires scope: `admin`
   */
  override var token: String? = null,

  /**
   * Filter logs to this service. Defaults to all logs.
   */
  val serviceId: String? = null,

  /**
   * Filter logs generated by this user\u2019s actions. Defaults to all logs.
   */
  val user: String? = null,

  /**
   * Filter logs to this Slack app. Defaults to all logs.
   */
  val appId: Int? = null,

  /**
   * Filter logs with this change type. Defaults to all logs.
   */
  val changeType: String? = null,

  val count: Int? = null,

  val page: Int? = null): SlackApiRequest