package com.github.seratch.jslack

object Constants {

  val SLACK_TEST_OAUTH_ACCESS_TOKEN = "SLACK_TEST_OAUTH_ACCESS_TOKEN"
  val SLACK_BOT_USER_TEST_OAUTH_ACCESS_TOKEN = "SLACK_BOT_USER_TEST_OAUTH_ACCESS_TOKEN"
}
